Support parsing of shortened function bodies
dlang-community/libdparse pull request #439
Opened 2021-03-28 06:17 UTC by Hackerpilot

Support for 2.096.0's new `-preview=shortenedMethods` syntax.

2021-03-28 06:21 UTC, Hackerpilot commented
Looks like the CI is failing because we're still using an ancient version of the allocators. We really need to fix that.

2021-05-27 09:43 UTC, TungstenHeart commented
That will pass if you rebase as @RazvanN7 has deactivated the tests relying on Meson in fbdf71b929a9f9bc982d0204f921371806e5d412.

2021-05-27 09:55 UTC, WebFreak001 requested changes

2021-05-27 09:55 UTC, WebFreak001 commented on src/dparse/ast.d
> +    /** */ size_t endLocation;
startLocation & endLocation never actually assigned (and obsolete since the introduction of the tokens slice)

2021-05-27 09:55 UTC, WebFreak001 commented on src/dparse/parser.d
> +            auto missingFunctionBody = parseMissingFunctionBody();
new/changed functionality without test?

2022-01-30 12:33 UTC, WebFreak001 approved these changes

2022-01-30 12:34 UTC, merged