Fix shortened FunctionBody and comment formatting
dlang-community/libdparse pull request #512
Opened 2023-12-29 16:02 UTC by zyebytevt

Nothing major, but the comment formatting produced invalid code since the three slashes at the beginning weren't written. Additionally, a shortened function body (`=>`) now also appears in formatting.

2023-12-29 17:06 UTC, WebFreak001 commented
add a test in the tests folder to show which issue this actually fixes

2023-12-29 17:06 UTC, WebFreak001 requested changes
needs test

2023-12-29 18:21 UTC, zyebytevt commented
Where should I add tests for this? My changes solely concern the `Formatter`, and if I'm not mistaken there appear to be no prior tests for it at all.

2023-12-29 19:15 UTC, WebFreak001 commented
ah sorry I thought this was in dfmt. In `libdparse` at the bottom there is a large unittest block where a bunch of code snippets are tested.

You will probably want something like
```d
testFormatNode!(FunctionDeclaration)(q{void someFunction() => whateverWasFixed()});
```

if you only provide a single string it is parsed and outputted again and checked that it matches the input exactly.

2023-12-29 20:14 UTC, zyebytevt commented
Alright, that should hopefully do it. Had to keep in mind various empty lines for the third check that the formatter produces, but that seems to be an issue (or intended) from before.

2023-12-30 22:38 UTC, WebFreak001 approved these changes
not ideal, but better than before and not really that essential to be perfect atm

2023-12-31 00:45 UTC, merged